-- Core schema for serverless remittance system
-- Safe to run multiple times (uses IF NOT EXISTS where possible)

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Users (Discord user as primary identity)
CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  discord_user_id TEXT UNIQUE NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Wallet balances in KRW (integer only)
CREATE TABLE IF NOT EXISTS user_balances (
  user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  balance_krw BIGINT NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Optional: per-user coin holdings (atomic units). Created by /코인구매, used by /송금.
CREATE TABLE IF NOT EXISTS user_crypto_balances (
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  symbol TEXT NOT NULL,
  atomic_balance NUMERIC(78,0) NOT NULL DEFAULT 0,
  atomic_scale INT NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY(user_id, symbol)
);

-- Ledger entries for auditability (credits/debits)
CREATE TABLE IF NOT EXISTS ledger_entries (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type TEXT NOT NULL CHECK (type IN ('deposit', 'purchase', 'transfer_fee', 'transfer', 'admin_adjust')),
  amount_krw BIGINT NOT NULL, -- +credit / -debit, integer
  ref_type TEXT NOT NULL,
  ref_id TEXT NOT NULL,
  meta JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ledger_user_time ON ledger_entries(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ledger_ref ON ledger_entries(ref_type, ref_id);

-- Deposit intents generated by /충전 (user gets a unique memo/code)
CREATE TABLE IF NOT EXISTS deposit_intents (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  deposit_code TEXT UNIQUE NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('open','used','expired')) DEFAULT 'open',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at TIMESTAMPTZ NOT NULL DEFAULT (now() + interval '2 hours')
);

CREATE INDEX IF NOT EXISTS idx_deposit_intents_user ON deposit_intents(user_id, created_at DESC);

-- iOS webhook logs (raw deposit events); dedupe by idempotency_key
CREATE TABLE IF NOT EXISTS ios_deposit_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  idempotency_key TEXT UNIQUE NOT NULL,
  device_id TEXT NOT NULL,
  bank_name TEXT,
  depositor_name TEXT,
  deposit_code TEXT,
  amount_krw BIGINT NOT NULL,
  occurred_at TIMESTAMPTZ NOT NULL,
  received_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  raw JSONB NOT NULL
);

-- Payment provider webhook events (generic)
CREATE TABLE IF NOT EXISTS payment_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  provider TEXT NOT NULL,
  idempotency_key TEXT UNIQUE NOT NULL,
  amount_krw BIGINT NOT NULL,
  discord_user_id TEXT,
  received_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  raw JSONB NOT NULL
);

-- Price snapshots (cached by cron)
CREATE TABLE IF NOT EXISTS price_snapshots (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  symbol TEXT NOT NULL, -- BTC, ETH...
  fx_usdkrw BIGINT NOT NULL, -- rate * 100 (two decimals) as integer, e.g., 132512 => 1325.12
  overseas_usd BIGINT NOT NULL, -- price_usd * 100 (two decimals)
  domestic_krw BIGINT NOT NULL, -- price_krw integer
  kimchi_premium_bps INT NOT NULL, -- computed bps
  buy_price_krw BIGINT NOT NULL, -- final user buy price per 1 coin (KRW integer)
  sources JSONB NOT NULL DEFAULT '{}'::jsonb,
  fetched_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_price_symbol_time ON price_snapshots(symbol, fetched_at DESC);

-- Inventory in atomic units (integer)
-- atomic_unit: BTC satoshi(1e8), ETH wei(1e18) can't fit? We store as DECIMAL text? To keep integer, store as NUMERIC.
-- Using NUMERIC(78,0) for safe big integer atomic units across chains.
CREATE TABLE IF NOT EXISTS inventory (
  symbol TEXT PRIMARY KEY,
  atomic_balance NUMERIC(78,0) NOT NULL DEFAULT 0,
  atomic_scale INT NOT NULL, -- e.g., BTC 8, ETH 18, XRP 6, TRX 6, LTC 8
  is_enabled BOOLEAN NOT NULL DEFAULT true,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Inventory valuation cached
CREATE TABLE IF NOT EXISTS inventory_valuation (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  total_krw BIGINT NOT NULL,
  per_symbol JSONB NOT NULL,
  evaluated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Purchase orders (user buys coin using KRW balance)
CREATE TABLE IF NOT EXISTS purchase_orders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  symbol TEXT NOT NULL,
  spend_krw BIGINT NOT NULL,
  buy_price_krw BIGINT NOT NULL, -- per 1 coin
  atomic_amount NUMERIC(78,0) NOT NULL, -- coin amount in atomic units delivered from inventory
  status TEXT NOT NULL CHECK (status IN ('filled','rejected')) NOT NULL,
  reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_purchase_user_time ON purchase_orders(user_id, created_at DESC);

-- Transfer requests (user requests on-chain transfer)
CREATE TABLE IF NOT EXISTS transfer_requests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  symbol TEXT NOT NULL,
  to_address TEXT NOT NULL,
  atomic_amount NUMERIC(78,0) NOT NULL,
  fee_krw BIGINT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('queued','processing','sent','failed')) DEFAULT 'queued',
  tx_hash TEXT,
  error TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_transfer_status_time ON transfer_requests(status, created_at ASC);

-- Minimal seed for supported coins
INSERT INTO inventory(symbol, atomic_balance, atomic_scale, is_enabled)
VALUES
  ('BTC', 0, 8, true),
  ('ETH', 0, 18, true),
  ('LTC', 0, 8, true),
  ('XRP', 0, 6, true),
  ('TRX', 0, 6, true)
ON CONFLICT (symbol) DO NOTHING;

